### ISSUE TITLE
Soft clipping

### ISSUE THREAD

**Issue by lskatz** [lskatz/lyve-SET#37]
Add soft clipping to avoid calling SNPs entirely based on the edges on reads

https://www.biostars.org/p/138399

**Comment by tseemann** [comment]
Soft clipping is essentially local alignment. This has its own issues near junctions and repeat regions - reads partially map but don't really belong there.

**Comment by lskatz** [comment]
You're right--I actually meant to remove this after thinking about this a bit more last year.  I think that Lyve-SET is doing this correctly with unambiguous mapping and Smith-Waterman alignment.
