### ISSUE TITLE
lyve-SET in a docker container

### ISSUE THREAD

**Issue by k-florek** [lskatz/lyve-SET#69]
I'm running into an issue that I can't seem to solve. I think it has to do with multi-threading? Hopefully, you might have some insight into this.

Here is the error:
`set_mergeVcf.sh: Output file can be found in /data/snp_tree/msa/out.pooled.vcf.gz
QSUB ERROR
256
launch_set.pl: Schedule::SGELK::command: ERROR with command: Inappropriate ioctl for device
  /usr/bin/perl /data/snp_tree/log/SGELK/qsub.414721.pl 
Stopped at /lyve-SET/scripts/../lib/Schedule/SGELK.pm line 661.
`

**Comment by nwflorek** [comment]
I think I solved the issue. The set of isolates I was looking at were all 0 SNPs apart.

**Comment by lskatz** [comment]
Ah!  That would be a problem then!

Am I understanding correctly that you are putting Lyve-SET into a Docker container?  If so, I would be interested in linking to that version or hosting it here.

**Comment by nwflorek** [comment]
Yes! It looks like I got it working in the container, although I'm still testing it. I had to make some modifications to the makefile. The system links only work if they are set to a relative path so I'm still checking to make sure I didn't break anything.

You can use it if you like. It's running a slightly older version of lyve-set so I'll post the link once I update it to be in line with the recent changes.

**Comment by nwflorek** [comment]
It looks like I've got version 1.1.4 working and the docker container can be pulled using `nwflorek/lyveset:1.1.4` [docker hub](https://hub.docker.com/r/nwflorek/lyveset/) I still have a weird issue with version 2.0.1 where varscan will randomly crash with the following error:

`Stopped at /lyve-SET/scripts/launch_varscan.pl line 111. QSUB ERROR 65280`

**Comment by lskatz** [comment]
I can't guarantee v2 yet and so I can't really answer you on the varscan bug at this time.  v1.1.4f is the most validated version; v1.1.4g is newer and is _probably_ stable.

@zorbax is that error from v1.1.4g?  What was your command?

**Comment by kapsakcj** [comment]
Bringing back this issue from the dead....Care to add the StaPH-B docker image to README.md and/or INSTALL.md?

```
docker pull staphb/lyveset:1.1.4f
# or 
docker pull staphb/lyveset:2.0.1

singularity build lyveset.1.1.4f.sif docker://staphb/lyveset:1.1.4f
# or
singularity build lyveset.2.0.1.sif docker://staphb/lyveset:2.0.1
```
The default `:latest` tag points to lyveset v2.0.1, but it might be best to leave that out if you'd prefer folks to use 1.1.4f.

https://hub.docker.com/r/staphb/lyveset

**Comment by kapsakcj** [comment]
and I betcha we could fix the Schedule::SGELK qsub errors by adding this to the dockerfile: `cpanm Schedule::SGE` I think its missing from the both docker images

**Comment by lskatz** [comment]
I'd argue that yes `:latest` should default to v1.1.4f or the latest version in v1.1.4 since there have been some patches.  I can add it.

Yes I think that cpanm command could help if SGELK is not being loaded correctly in the Lyve-SET installation.

Anyway I added mentions of containers in the documentation.  Thank you for the text.

**Comment by kapsakcj** [comment]
Awesome. I will point the default tag to 1.1.4f. We don't have a dockerfile for 1.1.4g or 2.0, but could make one.

I'll check on the Schedule::SGE perl module. Not sure if it was installed or not, I don't think it was in 1.1.4f.

**Comment by kapsakcj** [comment]
I added `Schedule::SGE` perl module to the 1.1.4f docker image, and it was also made the default dockerhub tag `latest`

**Comment by lskatz** [comment]
Thank you!
