### ISSUE TITLE
make PREFIX= isn't honoured?

### ISSUE THREAD

**Issue by tseemann** [lskatz/lyve-SET#76]
I ran `make PREFIX=/opt/lyve` and it ran to completion 
BUT
It only had a `bin` and `lib` dir with the vcf tools in it.

I was expecting it to install the whole system into that folder.

Did i do something wrong?

**Comment by lskatz** [comment]
Just saw this, sorry.  Years later.  No, it's a custom Makefile and it does not honor `PREFIX=`, sorry.
