### ISSUE TITLE
 Schedule::SGELK::command: ERROR with command: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by etuduri** [lskatz/lyve-SET#78]
Hello everyone, we have the next error message when we try to execute "make test" command. Could you help us?
Thanks in advance

launch_set.pl: Schedule::SGELK::command: Running /home/inei/anaconda3/bin/perl /home/inei/Lyve-SET/lambda/log/SGELK/qsub.57909.pl
QSUB ERROR
512
launch_set.pl: Schedule::SGELK::command: ERROR with command: Inappropriate ioctl for device
  /home/inei/anaconda3/bin/perl /home/inei/Lyve-SET/lambda/log/SGELK/qsub.57909.pl 
Stopped at /home/inei/Lyve-SET/scripts/../lib/Schedule/SGELK.pm line 661.
set_test.pl: ERROR: died while trying to run COMMAND
  launch_set.pl lambda --numcpus 1 --numnodes 20 
set_test.pl: See if you have the correct software installed for this command.
6400 at /home/inei/Lyve-SET/scripts/set_test.pl line 94.
Makefile:249: recipe for target 'test' failed
make: *** [test] Error 25

**Comment by lskatz** [comment]
It's difficult for me to debug when this is run within conda.  Do you want to deactivate conda, install Lyve-SET v1.1.4f, and then try again?

**Comment by etuduri** [comment]
Thank you very much for your help, I have been able to solve this problem and Lyve-Set now works !!. I have an issue with anaconda perl and the ubuntu perl.

**Comment by lskatz** [comment]
Phew!
