### ISSUE TITLE
mpileup generate empty file 

### ISSUE THREAD

**Issue by alantsangmb** [lskatz/lyve-SET#79]
Hi, I have installed lyve-SET-1.1.4f and I have run make env to set the perl and perl5lib environoment and no errors returns with "make check"

However, when I run lyve-SET on my fastq data, it returns following error:
###########################################################
launch_set.pl: variantCalls: /home/wgs/Tools/lyve-SET-1.1.4f/scripts/launch_varscan.pl /home/wgs/Mabs_lyve/bam/TH18008938.fastq.gz-FLAC029.gbk.sorted.bam --numcpus 16 --tempdir /home/wgs/Mabs_lyve/tmp --reference FLAC029.gbk.fasta --altfreq 0.75 --coverage 10  > /home/wgs/Mabs_lyve/vcf/TH18008938.fastq.gz-FLAC029.gbk.vcf
launch_set.pl: Schedule::SGELK::command: Running /usr/bin/perl /home/wgs/Mabs_lyve/log/SGELK/qsub.434103.pl
launch_varscan.pl: Creating a pileup /home/wgs/Mabs_lyve/tmp/TH18008938.fastq.gz-FLAC029.gbk.sorted.bam.mpileup
launch_varscan.pl: Running mpileup:
  echo "CP014956
" | xargs -P 16 -n 1 -I {} sh -c 'echo "MPileup on {}" >&2; samtools mpileup -f FLAC029.gbk.fasta -Q 0 -B  --region "{}" /home/wgs/Mabs_lyve/bam/TH18008938.fastq.gz-FLAC029.gbk.sorted.bam > /home/wgs/Mabs_lyve/tmp/TH18008938.fastq.gz-FLAC029.gbk.sorted.bam.$$.mpileup' 
MPileup on CP014956
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
launch_varscan.pl: Sorting mpileup results into a combined file
launch_varscan.pl: main::varscan: ERROR: the pileup is a zero-byte file
  /home/wgs/Mabs_lyve/tmp/TH18008938.fastq.gz-FLAC029.gbk.sorted.bam.mpileup 
Stopped at /home/wgs/Tools/lyve-SET-1.1.4f/scripts/launch_varscan.pl line 119.
QSUB ERROR
65280
launch_set.pl: Schedule::SGELK::command: ERROR with command: Inappropriate ioctl for device
  /usr/bin/perl /home/wgs/Mabs_lyve/log/SGELK/qsub.434103.pl 
Stopped at /home/wgs/Tools/lyve-SET-1.1.4f/scripts/../lib/Schedule/SGELK.pm line 661.
###########################################################

The mpileup file in the tmp directory was found to be empty. I execute samtools in the same terminal and it is version 0.1.19-96b5f2294a.

**Comment by lskatz** [comment]
This usually points to a difficulty in the fastq file.  Could you manually inspect it?  Some example commands are:

    ls -lh /home/wgs/Mabs_lyve/reads/TH18008938.fastq.gz
    zcat /home/wgs/Mabs_lyve/reads/TH18008938.fastq.gz | head # check that the first 10 lines look good
    # IDs should be every four lines
    zcat /home/wgs/Mabs_lyve/reads/TH18008938.fastq.gz | grep -n '^@' | head
    zcat /home/wgs/Mabs_lyve/reads/TH18008938.fastq.gz | grep -n '^@' | tail

And if those don't work, could you validate the fastq file with my script?

    git clone https://github.com/lskatz/ROSS
    zcat /home/wgs/Mabs_lyve/reads/TH18008938.fastq.gz | perl ROSS/scripts/friends_ross.pl --pe --min-length 1 --min-quality 1 --verbose

If that doesn't work, then we can look at the fastq file

**Comment by lskatz** [comment]
OH!  Here is some older troubleshooting documentation in case it helps too.  I think the tips here are still valid.  https://github.com/lskatz/lyve-SET/blob/master/docs/TROUBLESHOOTING.md#fastq-integrity

**Comment by alantsangmb** [comment]
Thank you for providing the troubleshooting page.
Problem solved if I cp the reference.fasta directly to the reference directory instead of using the symlink
