### ISSUE TITLE
pipeline error 

### ISSUE THREAD

**Issue by sekhwal** [lskatz/lyve-SET#82]
Hi,

I installed the pipeline using conda. However, it shows the an error while running the following command:

shuffleSplitReads.pl --numcpus 8 -o interleaved *.fastq.gz

error:

shuffleSplitReads.pl: main::readFastqs: ERROR: could not parse the read number from file Salm_010_r1.fastq.gz in the second part of the file =>_010_r1.fastq.gz<= 
Stopped at /home/anaconda3/envs/lyve/bin/shuffleSplitReads.pl line 50.

**Comment by lskatz** [comment]
Hi @sekhwal, thank you for bringing up this topic.  In order for the `shuffleSplitReads.pl` script to work, it has to parse the filenames.  It is looking for `_R1_`/`_R2_` or `_1.f`/`_2.f`.  In contrast, it looks like you have a custom suffix `_r1.fastq.gz` on this filename.  Please see #80 for more information.

**Comment by sekhwal** [comment]
I have updated my files name in such order (Salm_010_R1_001.fastq.gz and Salm_010_R2_001.fastq.gz) and running the command. However, it is still showing the error. Please indicate the complete command.

shuffleSplitReads.pl --numcpus 8 -o interleaved _R1_/_R2_

errror:
shuffleSplitReads.pl: shuffleWorker(TID7): Looking for *
Use of uninitialized value in concatenation (.) or string at /home/anaconda3/envs/lyve/bin/shuffleSplitReads.pl line 93.
run_assembly_shuffleReads.pl: main::main: ERROR: Could not find file _R1_/_R2_ 
Stopped at /home/bmaurice/anaconda3/envs/lyve/bin/run_assembly_shuffleReads.pl line 24.
renamed 'interleaved/./.fastq.gz.tmp' -> 'interleaved/./.fastq.gz'

**Comment by lskatz** [comment]
It looks like instead of providing all files, you used `_R1_/_R2_`.  I believe that with the corrected command and with your new filenames, it should work.  Example command:

`shuffleSplitReads.pl --numcpus 8 -o interleaved *.fastq.gz`
