### ISSUE TITLE
Running lyve-SET on single-end fastq 

### ISSUE THREAD

**Issue by tbazilegith** [lskatz/lyve-SET#84]
Hi Iskatz,
I need to find some metrics of my assembly such as coverage, average read length, number of reads
I have single-end reads, how do run lyve-SET on them?
The documentation states paired-end reads must be shuffled. What is the command for single-end reads?
Thanks,
TJ

**Comment by lskatz** [comment]
Hi @tbazilegith, there is an option `--singleend` that you can use.

You can also use the CGP scripts included in Lyve-SET to determine read metrics, namely `run_assembly_readMetrics.pl`.
