### ISSUE TITLE
Variant Calling doesn't work

### ISSUE THREAD

**Issue by davidmaimoun** [lskatz/lyve-SET#85]
Hi, 

I get an error when the program reach variant calling:

launch_set.pl: Schedule::SGELK::command: Running /home/user1/miniconda3/envs/lyveset/bin/perl /home/user1/Desktop/test/lyveset/setTest/log/SGELK/qsub.521686.pl
sh: 1: varscan.sh: not found
launch_varscan.pl: main::main: ERROR: varscan.sh gave an error 
Stopped at /home/user1/miniconda3/envs/lyveset/bin/launch_varscan.pl line 54.
QSUB ERROR
32512

I checked in the bin directory, and I have the varscan.sh (but not the vcftools.sh).
I uninstalled and installed it again but still doesn't work.

Could you help me me please?

Thank you

**Comment by lskatz** [comment]
Hi, I'm not really in control of the conda installations.  See if you can remove conda from your current shell (deactivate everything) and then install using the installation instructions in README.md.

**Comment by davidmaimoun** [comment]
Hi Iskatz,
It's still doesn't work, but I'll manage to find out something
Thank you!
