### ISSUE TITLE
Make install failing at vcftools compilation

### ISSUE THREAD

**Issue by erikwolfsohn** [lskatz/lyve-SET#87]
[log.txt](https://github.com/lskatz/lyve-SET/files/10363402/log.txt)

Hi lskatz,

I'm getting a series of compilation errors, trying to install both the latest stable version and the cutting edge version from git. The errors are the same for both, so I think it might be an issue with my configuration or something I've overlooked.

I've attached the logfile from make install - using Ubuntu 20.04 on wsl2, gcc version 9.4.0

Thanks!
Erik

**Comment by erikwolfsohn** [comment]
I figured out what was going on : VCFTools 0.1.12b isn't compatible with C++ 11. The next release, 0.1.13 is - I compiled the pipeline with that version and hopefully it will work as a drop-in replacement.

**Comment by lskatz** [comment]
Ok I am so glad you were able to figure this out and that you were able to show it on this ticket, for anyone in the future.  Please let me know if this pops up again.

**Comment by erikwolfsohn** [comment]
Sure thing! I can confirm that building with VCFTools 0.1.13 did work, I was able to run the lambda dataset & the larger listeria test dataset successfully.
